language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then composer install --ignore-platform-reqs; else composer install; fi

script:
  - ./vendor/bin/phpunit
